### ISSUE TITLE
Unable to post an update

### ISSUE THREAD

**Issue by TheAlexandru** [Giveth/giveth-2#783]
When I try to post an update I get this error:

`{error: Error: Cannot read property 'id' of null
    at new t (https://giveth.io/app-7e5e795f9caa2977109e.j…}
error: Error: Cannot read property 'id' of null at new t (https://giveth.io/app-7e5e795f9caa2977109e.js:2:253697) at Object.next (https://giveth.io/app-7e5e795f9caa2977109e.js:2:232447) at g (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419233) at _ (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419739) at e.value (https://giveth.io/app-7e5e795f9caa2977109e.js:2:420292) at https://giveth.io/app-7e5e795f9caa2977109e.js:2:154488 at Array.forEach (<anonymous>) at Z (https://giveth.io/app-7e5e795f9caa2977109e.js:2:154456) at Object.next (https://giveth.io/app-7e5e795f9caa2977109e.js:2:155541) at g (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419233) at _ (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419739) at e.value (https://giveth.io/app-7e5e795f9caa2977109e.js:2:420292) at g (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419233) at _ (https://giveth.io/app-7e5e795f9caa2977109e.js:2:419739) at e.value (https://giveth.io/app-7e5e795f9caa2977109e.js:2:420292) at https://giveth.io/app-7e5e795f9caa2977109e.js:2:77645
__proto__: Object`

**Comment by divine-comedian** [comment]
bump! 

I tried to post an update today on staging and received a similar error the one above. 
Using Brave Browser on a clean cache.

![image](https://user-images.githubusercontent.com/67759413/117191820-003fdf00-adaf-11eb-9233-f09251bb013b.png)

**Comment by laurenluz** [comment]
double bump 👀 testing on next with clean cache on brave and I get:

![image](https://user-images.githubusercontent.com/75490971/118305758-a5407300-b4a5-11eb-94dc-e30dbb21cf38.png)

**Comment by divine-comedian** [comment]
@laurenluz 
testing Brave Browser, clean cache and cookies
on `next.giveth`
 I think it returns an error because 'Title' is empty.. nevertheless I fill in title 
and hit submit. continue to hit more errors... 

![image](https://user-images.githubusercontent.com/67759413/119266400-aade3d00-bbb8-11eb-9487-ac0c1ca07c41.png)
#### I noticed an error for addUpdate :point_down: 

![image](https://user-images.githubusercontent.com/67759413/119266390-a0bc3e80-bbb8-11eb-9501-1a486f9e9888.png)

**Comment by mateodaza** [comment]
omg this is such an edge case, our app doesn't like CRABS and I don't know why 😠

**Comment by divine-comedian** [comment]
I'm experiencing this on more of my projects currently on next.giveth. it's a bit concerning because even projects I made as recently as may 23rd are getting this error. Even stranger is that I have already made updates on this project and now for some reason it no longer works...

Maybe @cquinterom096  you have some insight? this could be related to some of the status or project ID stuff we were looking at.

![image](https://user-images.githubusercontent.com/67759413/122823458-61fbd000-d2ad-11eb-94d1-181db07ac27e.png)
